#  create a file called "~/.test_driven_lighting.conf"
# and add the following with your details
---
:hue_ip: 192.168.1.2
:hue_api_id: your_api_key_key
:my_lamp_id: 1
:bunny:
  :bunny_username: guest
  :bunny_password: guest
  :bunny_host: localhost:5672
